#
# Sera - OnePage Jekyll Theme
# Configuration File
#

# Information for compile
exclude: ["Gemfile", "README.md"]

# Sass configuration
sass:
  sass_dir: _scss

# Information for deploy
baseurl: ""

# the base hostname & protocol for your site
url: "http://localhost:4000"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: Elevando a Segurança Digital com Soluções de Penteste de Classe Mundial
# Website language
lang: pt-BR
# Header Title
header-title: Proteja-se do <strong>imprevisto.</strong>
# Header Tagline
headter-tagline: Soluções de Segurança e Penteste

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Proteja-se agora
  url: https://themeforest.net/collections/6069390-sera

# Secondary Buttons
header-secondary-button:
  title: Descubra Mais
  url: http://themeforest.net/user/ohkimur

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: your_email@example.com

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: https://themeforest.net/collections/6069390-sera

####################################
######  Global Social Links   ######
####################################
youtube: "#"
pinterest: "#"
facebook: "#"
twitter: "#"
google-plus: "#"
vimeo: "#"

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
# about-widget:
#  author-avatar: avatar-02.jpg
#  author-name: John Doe
#  author-tagline: Blog Author
#  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies.
#  author-social-links:
#    youtube: "#"
#    pinterest: "#"
#    facebook: "#"
#    twitter: "#"
#    google-plus: "#"

# Google Map JS api
key-api: YOUR_GOOGLE_MAP_API_KEY
map-text: Sera Google Map
map-lat: 44.4267674
map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Theme created by Ohkimur
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Bem-vindo à Ascese
about-description: Somos especialistas em segurança de dados e pentest, dedicados a proteger seu ambiente digital contra ameaças e vulnerabilidades. Nossa equipe altamente qualificada utiliza técnicas avançadas para identificar e mitigar riscos, garantindo que suas informações estejam sempre seguras. Confie na Ascese para elevar a segurança do seu negócio a um novo patamar..

#####################################
#############  Features  ############
#####################################
features-title: Serviços 
features-description: Protegemos seus clientes contra as ameaças digitais e a garantir a integridade dos seus dados.

#
# Features
#
features:
  # Feature
  - title: Avaliação de Vulnerabilidades e Pentest
    description: Realizamos avaliações de vulnerabilidades e testes de penetração (pentest) detalhados para identificar e corrigir falhas de segurança em suas redes, aplicativos e sistemas. Nossos especialistas simulam ataques reais para garantir que suas defesas estejam sempre à frente das ameaças.
    icon: pe-7s-note2

  # Feature
  - title: Monitoramento e Resposta a Incidentes 24/7
    description: Oferecemos um serviço de monitoramento contínuo e resposta a incidentes, operando 24 horas por dia, 7 dias por semana. Nossa equipe de segurança está sempre alerta para detectar e responder rapidamente a qualquer atividade suspeita, minimizando o impacto de possíveis incidentes de segurança.
    icon: pe-7s-alarm

  # Feature
  - title: Treinamento em Segurança Cibernética
    description: Capacitamos sua equipe com treinamentos em segurança cibernética personalizados, abordando as melhores práticas e técnicas de defesa. Nossos cursos abrangem desde a conscientização sobre phishing até a implementação de políticas de segurança robustas, fortalecendo a postura de segurança da sua organização.
    icon: pe-7s-study

#####################################
############  Portfolio  ############
#####################################
portfolio-title: Portfolio
portfolio-description: Maecenas tempus nec mi et placerat. Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis.

#Portfolio Grid

portfolio-categories:
 [Websites, Logo, Graphic Design, Development, Video, Photography]
 portfolio:
# Portfolio Item
 - title: S<span class="thin">era</span> Style
   categories: [Websites, Graphic Design]
   image: img-01.jpg
  url: "#"

 #Portfolio Item
 - title: S<span class="thin">era</span> Style
 categories: [Graphic Design, Logo, Websites]
  image: img-02.jpg
 url: "#"

# Portfolio Item
 - title: S<span class="thin">era</span> Style
   categories: [Graphic Design, Logo, Photography]
  image: img-03.jpg
  url: "#"

 #Portfolio Item
 - title: S<span class="thin">era</span> Style
 categories: [Websites, Video, Photography]
 image: img-04.jpg
  url: "#"

 #Portfolio Item
- title: S<span class="thin">era</span> Style
 categories: [Development, Logo]
 image: img-05.jpg
 url: "#"

 #Portfolio Item
- title: S<span class="thin">era</span> Style
 categories: [Development, Video]
 image: img-06.jpg
 url: "#"

 #Portfolio Item
- title: S<span class="thin">era</span> Style
 categories: [Websites, Graphic Design]
 image: img-07.jpg
 url: "#"

 #Portfolio Item
 - title: S<span class="thin">era</span> Style
 categories: [Websites, Video]
 image: img-08.jpg
 url: "#"

 #Portfolio Item
- title: S<span class="thin">era</span> Style
 categories: [Photography, Logo]
 image: img-09.jpg
 url: "#"

#####################################
##########  Core Features  ##########
#####################################
core-title: Serviços centrais 
core-description: Nossa missão é elevar a segurança do seu ambiente digital, fornecendo soluções inovadoras e suporte contínuo para proteger o que é mais importante para você. Confie na Ascese para manter sua empresa segura e à frente das ameaças cibernéticas.

#
# Core Features Left
#
core-features-left:
  # Feature
  - name: Gestão de Ativos
    description: CyberSecurity Attack Surface Management (CSAM)
    icon: pe-7s-key

  # Feature
  - name: Gerenciamento de Vulnerabilidades e Configuração
    description: Gerenciamento, Detecção e Resposta a Vulnerabilidades
    icon: pe-7s-shield

  # Feature
  - name: Remediação de Riscos
    description: Avaliação e Remediação Personalizada
    icon: pe-7s-hammer

  # Feature
  - name: Detecção e Resposta a Ameaças
    description: Detecção e Resposta na Nuvem
    icon: pe-7s-search

#
# Core Features Right
#
core-features-right:
  # Feature
  - name: Automatização de Tarefas de Segurança
    description: Automatize tarefas de segurança
    icon: pe-7s-config

  # Feature
  - name: Identificação e Remediação de Vulnerabilidades
    description: Identifique as vulnerabilidades que realmente importam
    icon:  pe-7s-attention

  # Feature
  - name: Gestão Proativa de Cargas de Trabalho
    description: Ajude as equipes de segurança e desenvolvimento 
    icon: pe-7s-refresh

  # Feature
  - name: Documentação e Redirecionamento de Informações
    description: Toda atividade é documentada e relatada detalhadamente
    icon: pe-7s-note2

#####################################
########### Testimonials ############
#####################################
testimonials-title: Testemunhos
testimonials-description: Testemunhos de algumas empresas que já ajudamos

#
# Testimonials
#
testimonials:
  # Client
  - name: Super Bock Group
    url: https://superbockgroup.com/
    url-text: superbockgroup.com
    avatar: logo1.png
    cite: Queremos expressar nossa profunda gratidão à Ascese pelo excepcional suporte em cibersegurança. Graças à sua dedicação e profissionalismo, conseguimos garantir a segurança dos nossos sistemas e a confiança dos nossos clientes. Continuaremos a contar com a Ascese para manter nossos padrões de excelência e segurança online
    logo-img: logo1.png

  # Client
  - name: Petrotec Group
    url: https://www.petrotec.eu/
    url-text: petrotec.eu
    avatar: logo2.png
    cite: A Petrotec Group agradece imensamente à Ascese pelo comprometimento e eficiência na proteção de nossos dados e sistemas. A parceria com a Ascese tem sido crucial para assegurar a integridade das nossas operações tecnológicas, permitindo-nos focar em fornecer soluções inovadoras para nossos clientes
    logo-img: codecanyon.png

  # Client
  - name: Science4you
    url: https://www.science4you.pt/
    url-text: science4you.pt
    avatar: avatar-03.jpg
    cite: Gostaríamos de agradecer à Ascese pelo excelente serviço de cibersegurança que tem nos proporcionado. A tranquilidade de saber que nossos dados e operações estão seguros nos permite continuar a inovar e oferecer brinquedos educativos de qualidade para as crianças. Obrigado, Ascese, por ser um pilar de confiança para nossa empresa
    logo-img: logo3.png

  # Client
  - name: Sanitana
    url: https://www.sanitana.pt/pt/
    url-text: sanitana.pt
    avatar: avatar-04.jpg
    cite: Nosso sincero agradecimento à Ascese pela parceria sólida e pela proteção contínua que oferece aos nossos sistemas. A segurança proporcionada pela Ascese é fundamental para que possamos focar no desenvolvimento e na oferta de produtos de alta qualidade para os nossos clientes. Estamos confiantes de que, com a Ascese ao nosso lado, continuaremos a crescer com segurança e eficiência
    logo-img: logo4.png

#####################################
############# Our Blog ##############
#####################################
#blog-title: Our Blog
#blog-description: Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#####################################
############### Team ################
#####################################
team-title: Conheça nosso time
team-description: Nosso time é composto por profissionais altamente qualificados e dedicados. Todos os membros possuem formação em Ciência da Computação e/ou vasta experiência na área de hacking ético. 

#
# Team Members
#
team:
  # Team Member
  - name: João Silva
    tagline: Graphic Designer
    avatar: funci1.jpg

    # Social Links
    youtube: "#"
    pinterest: "#"
    facebook: "#"
    twitter: "#"
    google-plus: "#"
    vimeo: "#"

  # Team Member
  - name: Pedro Sousa
    tagline: Developer
    avatar: func2.jpg

    # Social Links
    youtube: "#"
    pinterest: "#"
    facebook: "#"
    twitter: "#"
    google-plus: "#"
    vimeo: "#"

  # Team Member
  - name: Tiago Ferreira
    tagline: Hacker
    avatar: func3.jpg

    # Social Links
    youtube: "#"
    pinterest: "#"
    facebook: "#"
    twitter: "#"
    google-plus: "#"
    vimeo: "#"

  # Team Member
  - name: Luís Young
    tagline: Support Expert
    avatar: func4.jpg

    # Social Links
    youtube: "#"
    pinterest: "#"
    facebook: "#"
    twitter: "#"
    google-plus: "#"
    vimeo: "#"

#####################################
########## Pricing Tables ###########
#####################################
pricing-title: Tabela de preços
pricing-description: Nossa empresa oferece uma tabela de preços clara e competitiva para todos os serviços de cibersegurança

#
# Plan Personal
#
plan-personal-price: a partir de 1000 EUROS 
plan-personal-offer-1-title: 01 PSD Pack
plan-personal-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-offer-2-title: 100 Support Tickets
plan-personal-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-url: "#"

#
# Plan Business
#
plan-business-price: a partir de 10000 EUROS
plan-business-offer-1-title: 05 PSD Pack
plan-business-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-offer-2-title: 1000 Support Tickets
plan-business-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-url: "#"

#
# Plan Ultimate
#
plan-ultimate-price: $999
plan-ultimate-offer-1-title: 10 PSD Pack
plan-ultimate-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-offer-2-title: Support Unlimited
plan-ultimate-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-url: "#"

#####################################
############   Contact   ############
#####################################
contact-title: Contact Us
contact-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat.

#####################################
#############   Footer   ############
#####################################
footer-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat.
footer-copyright-text: Ascese
footer-copyright-url: https://github.com/ohkimur
footer-copyright-year: 2024
